server:
  port: 6969
spring:  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/adidb
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
